[project]
name = "Sava_Crush"
version = "1.0.0"
author = [
    {name = "Sava2008"}
]
description = "README.md"

[images]
gems = ["Blue_gem.png", "Cyan_gem.png", "Orange_gem.png", "Purple_gem.png", 
        "Red_gem.png", "Magenta_gem.png", "Green_gem.png", "Bruise_gem.png"]
explosives = ["Firework.png", "Bomb.png", "Lightning.png"]
icons = ["Icon.ico"]

[sounds]
success = ["Gem_sound.mp3", "Gem_sound2.mp3", 
           "Gem_sound3.mp3", "Gem_sound4.mp3"]
failure = ["Forbidden.mp3", "Forbidden2.mp3"]
explosives = ["Lightning_sound.mp3", "Bomb_sound.mp3",
              "Firework_sound.mp3"]
			 
[requirements]
code = [
		{name = "python", version = "3.13.5"},
		{name = "pygame", version = "2.6.1"}
]
executable = false